EXECUTE_PROCESS(COMMAND ${PYTHON_EXECUTABLE} setup.py sdist --formats zip --dist-dir ${TMP} WORKING_DIRECTORY "${SRC}")
EXECUTE_PROCESS(COMMAND ${PYTHON_EXECUTABLE} setup.py --fullname WORKING_DIRECTORY ${SRC} OUTPUT_VARIABLE _FULLNAME)
STRING(STRIP ${_FULLNAME} FULLNAME)
EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E tar x "${FULLNAME}.zip" WORKING_DIRECTORY ${TMP})

EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E copy_directory "${TMP}/${FULLNAME}" "${BUILD}")
